"""Built-in model profiles for popular embedding models."""

from .registry import ModelProfile, ModelFamily, ModelRegistry

BUILTIN_PROFILES = [
    # ── BERT Family ──────────────────────────────────────────────
    ModelProfile(
        name="bert-base-uncased",
        family=ModelFamily.BERT,
        vocab_size=30522,
        embedding_dim=768,
        recommended_ranks=[4, 8, 16, 24, 32, 48],
        default_rank=8,
        max_seq_len=512,
        padding_token_id=0,
        notes="BERT base (110M params). 30K vocab, 768-dim embeddings.",
    ),
    ModelProfile(
        name="bert-large-uncased",
        family=ModelFamily.BERT,
        vocab_size=30522,
        embedding_dim=1024,
        recommended_ranks=[4, 8, 16, 24, 32, 48],
        default_rank=8,
        max_seq_len=512,
        padding_token_id=0,
        notes="BERT large (340M params). 30K vocab, 1024-dim embeddings.",
    ),
    ModelProfile(
        name="bert-base-multilingual-uncased",
        family=ModelFamily.BERT,
        vocab_size=119547,
        embedding_dim=768,
        recommended_ranks=[8, 16, 24, 32, 48, 64],
        default_rank=16,
        max_seq_len=512,
        padding_token_id=0,
        notes="Multilingual BERT. 119K vocab → higher rank recommended.",
    ),

    # ── RoBERTa Family ───────────────────────────────────────────
    ModelProfile(
        name="roberta-base",
        family=ModelFamily.ROBERTA,
        vocab_size=50265,
        embedding_dim=768,
        recommended_ranks=[4, 8, 16, 24, 32, 48],
        default_rank=8,
        max_seq_len=512,
        padding_token_id=1,
        notes="RoBERTa base. 50K BPE vocab.",
    ),
    ModelProfile(
        name="roberta-large",
        family=ModelFamily.ROBERTA,
        vocab_size=50265,
        embedding_dim=1024,
        recommended_ranks=[4, 8, 16, 24, 32, 48],
        default_rank=8,
        max_seq_len=512,
        padding_token_id=1,
        notes="RoBERTa large. 50K BPE vocab, 1024-dim.",
    ),

    # ── DistilBERT ───────────────────────────────────────────────
    ModelProfile(
        name="distilbert-base-uncased",
        family=ModelFamily.DISTILBERT,
        vocab_size=30522,
        embedding_dim=768,
        max_seq_len=512,
        padding_token_id=0,
        notes="Distilled BERT. Same vocab/emb as BERT base, smaller encoder.",
    ),

    # ── DeBERTa ──────────────────────────────────────────────────
    ModelProfile(
        name="deberta-v3-base",
        family=ModelFamily.DEBERTA,
        vocab_size=128000,
        embedding_dim=768,
        recommended_ranks=[8, 16, 24, 32, 48, 64],
        default_rank=16,
        max_seq_len=512,
        padding_token_id=0,
        notes="DeBERTaV3 base. 128K vocab → larger rank recommended.",
    ),
    ModelProfile(
        name="deberta-v3-large",
        family=ModelFamily.DEBERTA,
        vocab_size=128000,
        embedding_dim=1024,
        recommended_ranks=[8, 16, 24, 32, 48, 64],
        default_rank=16,
        max_seq_len=512,
        padding_token_id=0,
        notes="DeBERTaV3 large. 128K vocab, 1024-dim.",
    ),

    # ── ELECTRA ──────────────────────────────────────────────────
    ModelProfile(
        name="electra-base-discriminator",
        family=ModelFamily.ELECTRA,
        vocab_size=30522,
        embedding_dim=768,
        max_seq_len=512,
        padding_token_id=0,
        notes="ELECTRA base. Same shape as BERT base.",
    ),

    # ── MPNet ────────────────────────────────────────────────────
    ModelProfile(
        name="microsoft/mpnet-base",
        family=ModelFamily.MPNET,
        vocab_size=30527,
        embedding_dim=768,
        max_seq_len=512,
        padding_token_id=1,
        notes="MPNet base. Very similar to BERT base.",
    ),

    # ── GPT-2 Family ─────────────────────────────────────────────
    ModelProfile(
        name="gpt2",
        family=ModelFamily.GPT2,
        vocab_size=50257,
        embedding_dim=768,
        recommended_ranks=[4, 8, 16, 24, 32, 48],
        default_rank=8,
        max_seq_len=1024,
        notes="GPT-2 small (124M). 50K BPE vocab.",
    ),
    ModelProfile(
        name="gpt2-medium",
        family=ModelFamily.GPT2,
        vocab_size=50257,
        embedding_dim=1024,
        recommended_ranks=[4, 8, 16, 24, 32, 48],
        default_rank=8,
        max_seq_len=1024,
        notes="GPT-2 medium (355M). 50K vocab, 1024-dim.",
    ),
    ModelProfile(
        name="gpt2-large",
        family=ModelFamily.GPT2,
        vocab_size=50257,
        embedding_dim=1280,
        recommended_ranks=[8, 16, 24, 32, 48, 64],
        default_rank=16,
        max_seq_len=1024,
        notes="GPT-2 large (774M). 50K vocab, 1280-dim.",
    ),
    ModelProfile(
        name="gpt2-xl",
        family=ModelFamily.GPT2,
        vocab_size=50257,
        embedding_dim=1600,
        recommended_ranks=[8, 16, 24, 32, 48, 64],
        default_rank=16,
        max_seq_len=1024,
        notes="GPT-2 XL (1.5B). 50K vocab, 1600-dim.",
    ),

    # ── OPT Family ───────────────────────────────────────────────
    ModelProfile(
        name="facebook/opt-125m",
        family=ModelFamily.OPT,
        vocab_size=50272,
        embedding_dim=768,
        max_seq_len=2048,
        padding_token_id=1,
        notes="Meta OPT-125M. Similar to GPT-2.",
    ),
    ModelProfile(
        name="facebook/opt-1.3b",
        family=ModelFamily.OPT,
        vocab_size=50272,
        embedding_dim=2048,
        recommended_ranks=[8, 16, 24, 32, 48, 64],
        default_rank=16,
        max_seq_len=2048,
        padding_token_id=1,
        notes="Meta OPT-1.3B. 50K vocab, 2048-dim.",
    ),

    # ── LLaMA Family ─────────────────────────────────────────────
    ModelProfile(
        name="meta-llama/Llama-2-7b-hf",
        family=ModelFamily.LLAMA,
        vocab_size=32000,
        embedding_dim=4096,
        recommended_ranks=[16, 24, 32, 48, 64, 96],
        default_rank=24,
        max_seq_len=4096,
        notes="LLaMA 2 7B. 32K vocab, 4096-dim → high rank needed.",
    ),
    ModelProfile(
        name="meta-llama/Llama-2-13b-hf",
        family=ModelFamily.LLAMA,
        vocab_size=32000,
        embedding_dim=5120,
        recommended_ranks=[16, 24, 32, 48, 64, 96],
        default_rank=32,
        max_seq_len=4096,
        notes="LLaMA 2 13B. 32K vocab, 5120-dim.",
    ),
    ModelProfile(
        name="meta-llama/Llama-2-70b-hf",
        family=ModelFamily.LLAMA,
        vocab_size=32000,
        embedding_dim=8192,
        recommended_ranks=[32, 48, 64, 96, 128],
        default_rank=48,
        max_seq_len=4096,
        notes="LLaMA 2 70B. 32K vocab, 8192-dim → moderate compression.",
    ),
    ModelProfile(
        name="meta-llama/Meta-Llama-3-8B",
        family=ModelFamily.LLAMA,
        vocab_size=128256,
        embedding_dim=4096,
        recommended_ranks=[16, 24, 32, 48, 64, 96],
        default_rank=32,
        max_seq_len=8192,
        padding_token_id=128255,
        notes="LLaMA 3 8B. 128K tokenizer → larger rank for good compression.",
    ),
    ModelProfile(
        name="meta-llama/Meta-Llama-3-70B",
        family=ModelFamily.LLAMA,
        vocab_size=128256,
        embedding_dim=8192,
        recommended_ranks=[32, 48, 64, 96, 128],
        default_rank=48,
        max_seq_len=8192,
        padding_token_id=128255,
        notes="LLaMA 3 70B. 128K vocab, 8192-dim.",
    ),
    ModelProfile(
        name="codellama/CodeLlama-7b-hf",
        family=ModelFamily.CODELLAMA,
        vocab_size=32016,
        embedding_dim=4096,
        recommended_ranks=[16, 24, 32, 48, 64, 96],
        default_rank=24,
        max_seq_len=16384,
        notes="CodeLlama 7B. 32K vocab, 4096-dim, 16K context.",
    ),

    # ── Mistral Family ───────────────────────────────────────────
    ModelProfile(
        name="mistralai/Mistral-7B-v0.1",
        family=ModelFamily.MISTRAL,
        vocab_size=32000,
        embedding_dim=4096,
        recommended_ranks=[16, 24, 32, 48, 64, 96],
        default_rank=24,
        max_seq_len=8192,
        notes="Mistral 7B. 32K vocab, 4096-dim.",
    ),
    ModelProfile(
        name="mistralai/Mixtral-8x7B-v0.1",
        family=ModelFamily.MIXTRAL,
        vocab_size=32000,
        embedding_dim=4096,
        recommended_ranks=[16, 24, 32, 48, 64, 96],
        default_rank=24,
        max_seq_len=32768,
        notes="Mixtral 8x7B MoE. 32K vocab, 4096-dim.",
    ),

    # ── Falcon Family ────────────────────────────────────────────
    ModelProfile(
        name="tiiuae/falcon-7b",
        family=ModelFamily.FALCON,
        vocab_size=65024,
        embedding_dim=4544,
        recommended_ranks=[8, 16, 24, 32, 48, 64],
        default_rank=16,
        max_seq_len=2048,
        notes="Falcon 7B. 65K vocab, 4544-dim.",
    ),
    ModelProfile(
        name="tiiuae/falcon-40b",
        family=ModelFamily.FALCON,
        vocab_size=65024,
        embedding_dim=8192,
        recommended_ranks=[16, 24, 32, 48, 64, 96],
        default_rank=32,
        max_seq_len=2048,
        notes="Falcon 40B. 65K vocab, 8192-dim.",
    ),

    # ── BLOOM Family ─────────────────────────────────────────────
    ModelProfile(
        name="bigscience/bloom-560m",
        family=ModelFamily.BLOOM,
        vocab_size=250880,
        embedding_dim=1024,
        recommended_ranks=[16, 24, 32, 48, 64, 96],
        default_rank=32,
        max_seq_len=2048,
        notes="BLOOM 560M. 250K vocab → high rank essential.",
    ),
    ModelProfile(
        name="bigscience/bloom-7b1",
        family=ModelFamily.BLOOM,
        vocab_size=250880,
        embedding_dim=4096,
        recommended_ranks=[32, 48, 64, 96, 128],
        default_rank=48,
        max_seq_len=2048,
        notes="BLOOM 7.1B. 250K vocab, 4096-dim. Very large vocab.",
    ),

    # ── Gemma Family ─────────────────────────────────────────────
    ModelProfile(
        name="google/gemma-7b",
        family=ModelFamily.GEMMA,
        vocab_size=256000,
        embedding_dim=3072,
        recommended_ranks=[16, 24, 32, 48, 64, 96],
        default_rank=32,
        max_seq_len=8192,
        padding_token_id=0,
        notes="Gemma 7B by Google. 256K vocab → compression essential.",
    ),
    ModelProfile(
        name="google/gemma-2b",
        family=ModelFamily.GEMMA,
        vocab_size=256000,
        embedding_dim=2048,
        recommended_ranks=[16, 24, 32, 48, 64],
        default_rank=24,
        max_seq_len=8192,
        padding_token_id=0,
        notes="Gemma 2B. 256K vocab, 2048-dim.",
    ),

    # ── Phi Family ───────────────────────────────────────────────
    ModelProfile(
        name="microsoft/phi-2",
        family=ModelFamily.PHI,
        vocab_size=51200,
        embedding_dim=2560,
        recommended_ranks=[8, 16, 24, 32, 48],
        default_rank=16,
        max_seq_len=2048,
        notes="Phi-2 (2.7B). 51K vocab, 2560-dim.",
    ),

    # ── Qwen2 Family ─────────────────────────────────────────────
    ModelProfile(
        name="Qwen/Qwen2-7B",
        family=ModelFamily.QWEN2,
        vocab_size=152064,
        embedding_dim=3584,
        recommended_ranks=[16, 24, 32, 48, 64, 96],
        default_rank=32,
        max_seq_len=32768,
        notes="Qwen2 7B. 152K vocab, 3584-dim.",
    ),

    # ── Encoder-Decoder ──────────────────────────────────────────
    ModelProfile(
        name="t5-small",
        family=ModelFamily.T5,
        vocab_size=32128,
        embedding_dim=512,
        recommended_ranks=[4, 8, 16, 24, 32],
        default_rank=8,
        max_seq_len=512,
        padding_token_id=0,
        notes="T5 small. 32K vocab, 512-dim — smaller model, good for testing.",
    ),
    ModelProfile(
        name="t5-base",
        family=ModelFamily.T5,
        vocab_size=32128,
        embedding_dim=768,
        max_seq_len=512,
        padding_token_id=0,
        notes="T5 base. Same shape as BERT base.",
    ),
    ModelProfile(
        name="facebook/bart-base",
        family=ModelFamily.BART,
        vocab_size=50265,
        embedding_dim=768,
        max_seq_len=1024,
        padding_token_id=1,
        notes="BART base. Same shape as RoBERTa base.",
    ),
    ModelProfile(
        name="xlnet-base-cased",
        family=ModelFamily.XLNET,
        vocab_size=32000,
        embedding_dim=768,
        max_seq_len=512,
        padding_token_id=5,
        notes="XLNet base. 32K vocab, 768-dim.",
    ),
    ModelProfile(
        name="camembert-base",
        family=ModelFamily.CAMEMBERT,
        vocab_size=32000,
        embedding_dim=768,
        max_seq_len=512,
        padding_token_id=1,
        notes="CamemBERT base (French). 32K vocab, 768-dim.",
    ),
    ModelProfile(
        name="albert-base-v2",
        family=ModelFamily.ALBERT,
        vocab_size=30000,
        embedding_dim=128,
        recommended_ranks=[2, 4, 8, 16],
        default_rank=4,
        max_seq_len=512,
        padding_token_id=0,
        notes="ALBERT base. Small 128-dim embeddings — already very compact.",
    ),

    # ── GPT-J / GPT-NeoX ──────────────────────────────────────────
    ModelProfile(
        name="EleutherAI/gpt-j-6b",
        family=ModelFamily.GPT2,
        vocab_size=50400,
        embedding_dim=4096,
        recommended_ranks=[8, 16, 24, 32, 48],
        default_rank=16,
        max_seq_len=2048,
        notes="GPT-J 6B. 50K vocab, 4096-dim.",
    ),
    ModelProfile(
        name="EleutherAI/gpt-neox-20b",
        family=ModelFamily.GPT2,
        vocab_size=50432,
        embedding_dim=6144,
        recommended_ranks=[16, 24, 32, 48, 64],
        default_rank=24,
        max_seq_len=2048,
        notes="GPT-NeoX 20B. 50K vocab, 6144-dim.",
    ),

    # ── Pythia (EleutherAI) ────────────────────────────────────────
    ModelProfile(
        name="EleutherAI/pythia-6.9b",
        family=ModelFamily.GPT2,
        vocab_size=50432,
        embedding_dim=4096,
        recommended_ranks=[8, 16, 24, 32, 48],
        default_rank=16,
        max_seq_len=2048,
        notes="Pythia 6.9B. 50K vocab, 4096-dim.",
    ),
    ModelProfile(
        name="EleutherAI/pythia-12b",
        family=ModelFamily.GPT2,
        vocab_size=50432,
        embedding_dim=5120,
        recommended_ranks=[16, 24, 32, 48, 64],
        default_rank=24,
        max_seq_len=2048,
        notes="Pythia 12B. 50K vocab, 5120-dim.",
    ),

    # ── StarCoder (BigCode) ───────────────────────────────────────
    ModelProfile(
        name="bigcode/starcoder",
        family=ModelFamily.CODELLAMA,
        vocab_size=49152,
        embedding_dim=8192,
        recommended_ranks=[16, 24, 32, 48, 64],
        default_rank=32,
        max_seq_len=8192,
        padding_token_id=0,
        notes="StarCoder 15.5B. 49K vocab, 8192-dim.",
    ),

    # ── DBRX (Databricks) ─────────────────────────────────────────
    ModelProfile(
        name="databricks/dbrx-base",
        family=ModelFamily.MIXTRAL,
        vocab_size=100352,
        embedding_dim=4096,
        recommended_ranks=[16, 24, 32, 48, 64],
        default_rank=24,
        max_seq_len=32768,
        notes="DBRX MoE. 100K vocab, 4096-dim.",
    ),

    # ── Command R (Cohere) ────────────────────────────────────────
    ModelProfile(
        name="CohereForAI/c4ai-command-r-v01",
        family=ModelFamily.CUSTOM,
        vocab_size=262144,
        embedding_dim=4096,
        recommended_ranks=[32, 48, 64, 96, 128],
        default_rank=48,
        max_seq_len=131072,
        notes="Command R. 262K vocab → high rank essential.",
    ),

    # ── Jamba (AI21) ──────────────────────────────────────────────
    ModelProfile(
        name="ai21labs/Jamba-v0.1",
        family=ModelFamily.MIXTRAL,
        vocab_size=65536,
        embedding_dim=4096,
        recommended_ranks=[16, 24, 32, 48, 64],
        default_rank=24,
        max_seq_len=256000,
        notes="Jamba MoE + SSM hybrid. 65K vocab, 4096-dim.",
    ),

    # ── MPT (MosaicML) ────────────────────────────────────────────
    ModelProfile(
        name="mosaicml/mpt-7b",
        family=ModelFamily.CUSTOM,
        vocab_size=50432,
        embedding_dim=4096,
        recommended_ranks=[8, 16, 24, 32, 48],
        default_rank=16,
        max_seq_len=2048,
        padding_token_id=0,
        notes="MPT 7B. 50K vocab, 4096-dim.",
    ),

    # ── Yi (01.AI) ────────────────────────────────────────────────
    ModelProfile(
        name="01-ai/Yi-6B",
        family=ModelFamily.LLAMA,
        vocab_size=64000,
        embedding_dim=4096,
        recommended_ranks=[16, 24, 32, 48, 64],
        default_rank=24,
        max_seq_len=4096,
        notes="Yi 6B. 64K vocab, 4096-dim.",
    ),
    ModelProfile(
        name="01-ai/Yi-34B",
        family=ModelFamily.LLAMA,
        vocab_size=64000,
        embedding_dim=7168,
        recommended_ranks=[24, 32, 48, 64, 96],
        default_rank=32,
        max_seq_len=4096,
        notes="Yi 34B. 64K vocab, 7168-dim.",
    ),

    # ── DeepSeek ──────────────────────────────────────────────────
    ModelProfile(
        name="deepseek-ai/deepseek-llm-7b-base",
        family=ModelFamily.LLAMA,
        vocab_size=102400,
        embedding_dim=4096,
        recommended_ranks=[16, 24, 32, 48, 64],
        default_rank=32,
        max_seq_len=4096,
        notes="DeepSeek LLM 7B. 102K vocab → higher rank needed.",
    ),
    ModelProfile(
        name="deepseek-ai/deepseek-v2",
        family=ModelFamily.LLAMA,
        vocab_size=102400,
        embedding_dim=7168,
        recommended_ranks=[24, 32, 48, 64, 96],
        default_rank=48,
        max_seq_len=16384,
        notes="DeepSeek V2. 102K vocab, 7168-dim → significant compression opportunity.",
    ),

    # ── StableLM (Stability AI) ───────────────────────────────────
    ModelProfile(
        name="stabilityai/stablelm-base-alpha-3b",
        family=ModelFamily.GPT2,
        vocab_size=50688,
        embedding_dim=4096,
        recommended_ranks=[8, 16, 24, 32, 48],
        default_rank=16,
        max_seq_len=4096,
        notes="StableLM 3B Alpha. 50K vocab, 4096-dim.",
    ),

    # ── Zephyr (HuggingFace H4) ───────────────────────────────────
    ModelProfile(
        name="HuggingFaceH4/zephyr-7b-beta",
        family=ModelFamily.MISTRAL,
        vocab_size=32000,
        embedding_dim=4096,
        recommended_ranks=[16, 24, 32, 48, 64],
        default_rank=24,
        max_seq_len=8192,
        notes="Zephyr 7B Beta (Mistral fine-tune). 32K vocab, 4096-dim.",
    ),

    # ── Solar (Upstage) ───────────────────────────────────────────
    ModelProfile(
        name="upstage/SOLAR-10.7B-v1.0",
        family=ModelFamily.LLAMA,
        vocab_size=32000,
        embedding_dim=4096,
        recommended_ranks=[16, 24, 32, 48, 64],
        default_rank=24,
        max_seq_len=4096,
        notes="SOLAR 10.7B. 32K vocab, 4096-dim.",
    ),

    # ── XVERSE ────────────────────────────────────────────────────
    ModelProfile(
        name="xverse/XVERSE-7B",
        family=ModelFamily.LLAMA,
        vocab_size=100032,
        embedding_dim=4096,
        recommended_ranks=[16, 24, 32, 48, 64],
        default_rank=32,
        max_seq_len=8192,
        notes="XVERSE 7B. 100K vocab, 4096-dim.",
    ),

    # ── Qwen 2.5 (more recent) ────────────────────────────────────
    ModelProfile(
        name="Qwen/Qwen2.5-7B",
        family=ModelFamily.QWEN2,
        vocab_size=152064,
        embedding_dim=3584,
        recommended_ranks=[16, 24, 32, 48, 64, 96],
        default_rank=32,
        max_seq_len=131072,
        notes="Qwen 2.5 7B. 152K vocab, 3584-dim, 128K context.",
    ),
    ModelProfile(
        name="Qwen/Qwen2.5-72B",
        family=ModelFamily.QWEN2,
        vocab_size=152064,
        embedding_dim=8192,
        recommended_ranks=[32, 48, 64, 96, 128],
        default_rank=48,
        max_seq_len=131072,
        notes="Qwen 2.5 72B. 152K vocab, 8192-dim, 128K context.",
    ),

    # ── LLaMA 3.1/3.2 (newer) ─────────────────────────────────────
    ModelProfile(
        name="meta-llama/Meta-Llama-3.1-8B",
        family=ModelFamily.LLAMA,
        vocab_size=128256,
        embedding_dim=4096,
        recommended_ranks=[16, 24, 32, 48, 64, 96],
        default_rank=32,
        max_seq_len=131072,
        padding_token_id=128255,
        notes="LLaMA 3.1 8B. 128K vocab, 128K context.",
    ),
    ModelProfile(
        name="meta-llama/Llama-3.2-3B",
        family=ModelFamily.LLAMA,
        vocab_size=128256,
        embedding_dim=3072,
        recommended_ranks=[16, 24, 32, 48, 64],
        default_rank=24,
        max_seq_len=131072,
        padding_token_id=128255,
        notes="LLaMA 3.2 3B. 128K vocab, 3072-dim.",
    ),

    # ── Granite (IBM) ─────────────────────────────────────────────
    ModelProfile(
        name="ibm/granite-7b-base",
        family=ModelFamily.CUSTOM,
        vocab_size=49152,
        embedding_dim=4096,
        recommended_ranks=[8, 16, 24, 32, 48],
        default_rank=16,
        max_seq_len=4096,
        notes="IBM Granite 7B. 49K vocab, 4096-dim.",
    ),
]

for _p in BUILTIN_PROFILES:
    ModelRegistry.register(_p)
