"""Magic numbers extracted as named constants for maintainability."""

DEFAULT_SVD_INIT_STEPS = 700
DEFAULT_SVD_INIT_BATCH_SIZE = 32768
DEFAULT_TR_SVD_STEPS = 1000
DEFAULT_TR_SVD_BATCH_SIZE = 16384
DEFAULT_DISTILL_BATCH_SIZE = 16384
DEFAULT_DISTILL_LR = 0.01
DEFAULT_ALS_SAMPLE_SIZE = 1024
DEFAULT_ALS_PADDING_LIMIT_BYTES = 1.5e9
DEFAULT_GAUGE_FIX_INTERVAL = 1000
DEFAULT_MIN_RANK = 2
DEFAULT_TAPER_FACTOR = 0.5
DEFAULT_MAX_PADDING_PCT = 0.15
DEFAULT_EMBEDDING_DIM = 768
DEFAULT_VOCAB_SIZE = 50257
DEFAULT_LR = 0.01
DEFAULT_WEIGHT_DECAY = 1e-5
DEFAULT_LR_PCT_START = 0.1
DEFAULT_MAX_MODEL_SIZE_GB = 5.0
DEFAULT_DOWNLOAD_TIMEOUT = 300